name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Build with PyInstaller
      run: |
        # 检查 akshare 路径（可根据实际情况调整）
        $aksharePath = ".venv\Lib\site-packages\akshare"
        if (!(Test-Path $aksharePath)) {
          $aksharePath = "Lib\site-packages\akshare"
        }
        pyinstaller --onefile --add-data "$aksharePath;akshare" --noconsole --icon=logo.ico main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MoneySeek-${{ matrix.python-version }}
        path: dist/
